(function() {var implementors = {};
implementors["extprim"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.Not.html\" title=\"trait core::ops::bit::Not\">Not</a> for <a class=\"struct\" href=\"extprim/u128/struct.u128.html\" title=\"struct extprim::u128::u128\">u128</a>",synthetic:false,types:["extprim::u128::u128"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.Not.html\" title=\"trait core::ops::bit::Not\">Not</a> for <a class=\"struct\" href=\"extprim/traits/struct.Wrapping.html\" title=\"struct extprim::traits::Wrapping\">Wrapping</a>&lt;<a class=\"struct\" href=\"extprim/u128/struct.u128.html\" title=\"struct extprim::u128::u128\">u128</a>&gt;",synthetic:false,types:["extprim::traits::Wrapping"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.Not.html\" title=\"trait core::ops::bit::Not\">Not</a> for <a class=\"struct\" href=\"extprim/i128/struct.i128.html\" title=\"struct extprim::i128::i128\">i128</a>",synthetic:false,types:["extprim::i128::i128"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.Not.html\" title=\"trait core::ops::bit::Not\">Not</a> for <a class=\"struct\" href=\"extprim/traits/struct.Wrapping.html\" title=\"struct extprim::traits::Wrapping\">Wrapping</a>&lt;<a class=\"struct\" href=\"extprim/i128/struct.i128.html\" title=\"struct extprim::i128::i128\">i128</a>&gt;",synthetic:false,types:["extprim::traits::Wrapping"]},];
implementors["num_bigint"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.Not.html\" title=\"trait core::ops::bit::Not\">Not</a> for <a class=\"struct\" href=\"num_bigint/struct.BigInt.html\" title=\"struct num_bigint::BigInt\">BigInt</a>",synthetic:false,types:["num_bigint::bigint::BigInt"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.Not.html\" title=\"trait core::ops::bit::Not\">Not</a> for &amp;'a <a class=\"struct\" href=\"num_bigint/struct.BigInt.html\" title=\"struct num_bigint::BigInt\">BigInt</a>",synthetic:false,types:["num_bigint::bigint::BigInt"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
